# Generated by Django 6.1.2 on 2026-10-09 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('organization', models.CharField(max_length=220)),
                ('year', models.CharField(max_length=40)),
                ('details', models.TextField(blank=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=180)),
                ('institution', models.CharField(max_length=220)),
                ('location', models.CharField(max_length=150)),
                ('period', models.CharField(max_length=80)),
                ('result', models.CharField(blank=True, max_length=180)),
                ('thesis', models.CharField(blank=True, max_length=300)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', '-period'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=180)),
                ('organization', models.CharField(max_length=220)),
                ('location', models.CharField(max_length=150)),
                ('period', models.CharField(max_length=80)),
                ('summary', models.TextField()),
                ('highlights', models.TextField(help_text='Enter one achievement or responsibility per line.')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'experiences',
                'ordering': ['display_order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=180)),
                ('department', models.CharField(max_length=180)),
                ('institution', models.CharField(max_length=180)),
                ('location', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('biography', models.TextField()),
                ('research_interests', models.TextField(help_text='Enter one research interest per line.')),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('orcid_url', models.URLField(blank=True)),
                ('scholar_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'portfolio profile',
                'verbose_name_plural': 'portfolio profile',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('authors', models.CharField(max_length=500)),
                ('venue', models.CharField(max_length=300)),
                ('year', models.PositiveSmallIntegerField()),
                ('publication_type', models.CharField(choices=[('journal', 'Journal article'), ('conference', 'Conference paper'), ('book_chapter', 'Book chapter')], max_length=20)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('doi_url', models.URLField(blank=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['-year', 'display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('category', models.CharField(max_length=100)),
                ('period', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('result', models.CharField(blank=True, max_length=300)),
                ('outcome', models.CharField(blank=True, max_length=180)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'skill categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_order', models.PositiveSmallSmallIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio.skillcategory')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
